### ISSUE TITLE
Cannot package django-supervisor with py2app due to version.txt

### ISSUE THREAD

**Issue by kevinlondon** [rfk/django-supervisor#31]
If I use py2app to package a Django application with django-supervisor, it will not run as it's looking for version.txt within the site-packages.zip directory. I can work around this by hard-coding in the version number in the lines mentioned below but I do not believe this is a great solution. I will work to figure out a patch.

``` python
Traceback (most recent call last):
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/djsupervisor/management/commands/supervisor.py", line 39, in <module>
    from supervisor import supervisord, supervisorctl
  File "supervisor/supervisord.pyc", line 41, in <module>
  File "supervisor/options.pyc", line 56, in <module>
IOError: [Errno 20] Not a directory: '/Users/kevinlondon/dropbox/programming/python/django/sample_app/dist/sample_app.app/Contents/Resources/lib/python2.7/site-packages.zip/supervisor/version.txt'
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
